### ISSUE TITLE
How to inference?

### ISSUE THREAD

**Issue by lucasjinreal** [lzccccc/SMOKE#10]
Does there any inference code ?

**Comment by lzccccc** [comment]
I guess you mean "Is there any inference code?"
The answer is Yes. Please check
https://github.com/lzccccc/SMOKE/blob/master/tools/plain_train_net.py#L73

**Comment by lzccccc** [comment]
You can download the weights from Google drive: https://drive.google.com/file/d/11VK8_HfR7t0wm-6dCNP5KS3Vh-Qm686-/view.

And you can inference it with `python tools/plain_train_net.py --eval-only --config-file "configs/smoke_gn_vector.yaml"
`
It will generates .txt file on test set. The visualization code is not provided.

Steps before are all included in README file. Another suggestion for you is to first read the README carefully instead of opening an issue and questioning others' work.

**Comment by lucasjinreal** [comment]
If I opensource it, I will write a code for intuitively prediction and visualize. Also your readme doesn't provide more information about inference steps.

**Comment by lzccccc** [comment]
Different people have different ways of doing things.
I already put everything including training/testing code and instructions in the repo.
And there are others who could understand and use it easily.
Use your own standard to require others is harsh...

**Comment by anoop54** [comment]
This is fantastic as it is! Please ignore these comments, I think you've done an incredible job for the community.
